### ISSUE TITLE
Allow users (of Waterfox) to be aware of a registration before the Service Worker becomes active

### ISSUE THREAD

**Issue by grahamperrin** [google/service-worker-detector#11]
## Enhancement request

Please, would you consider adding a user preference that allows an icon of Service Worker Detector to be seen whilst a worker is inactive?

I reckon, there need not be a GUI to the preference. A boolean in about:config might suffice. 

I can encourage someone in or around the Waterfox project to make a pull request. (I'd do so myself, but I don't have coding skills.)

## Background

Firefox Quantum benefits from its **page actions menu**, where Service Worker Detector can present itself whilst a worker is inactive.

Waterfox 56.2.0 does not have that benefit. 

### Perspectives

<https://www.reddit.com/comments/8hz93r/-/dyoabtb/> draws attention to the progressive, pro-Photon viewpoint of Waterfox project leader Alex Kontos – I assume that there'll be the page actions menu, and other things that are associated with Photon, in due course.

Somewhere between _acceptance_ of service workers (my viewpoint) and _blanket refusal_ (`dom.serviceWorkers.enabled` `false` and so on), there's a subset of users where _interest_ in service workers overlaps with _caution_ and sometimes, scepticism. Some people in this subset will appreciate a visual hint, from Service Worker Detector, that there's a registration.

**Comment by tomayac** [comment]
I think this is out of scope for the extension in its current form, as it's supposed to report on `active` Service Workers only.

You (or for what it's worth, the Waterfox folks) are free, however, to fork the extension and instead of reacting on `navigator.serviceWorker.controller`, that is, active Service Workers ([deeplink to where this happens](https://github.com/google/service-worker-detector/blob/cb78f3a4289d95a093dffaf6b02a8fb723762aba/contentscript.js#L54)), listen instead for:
- `ServiceWorkerRegistration.installing` ([docs](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/installing))
- `ServiceWorkerRegistration.waiting` ([docs](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/waiting))
- `ServiceWorkerRegistration/onupdatefound` ([docs](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/onupdatefound))

**Comment by grahamperrin** [comment]
@tomayac thanks! 

@MrAlex94 FYI: 

- https://redd.it/8m1pxr or 
- (new Reddit, screenshots inline) https://new.reddit.com/r/waterfox/comments/8m1pxr/service_worker_detection_in_waterfox/

I guess that sooner or later, a question there will lead to the information here.
