### ISSUE TITLE
[Firefox] does not work on YouTube

### ISSUE THREAD

**Issue by ghost** [google/service-worker-detector#14]
In Firefox beta 71, because of some Firefox quirk(?), as commented in source:

>// ⚠️ TODO: Why does Firefox require ```option.toProxyScript```?

>Error: "Unexpected property toProxyScript"
    <anonymous> moz-extension://2df93d6f-ffc3-4d19-8240-a4fd87b6ade2/contentscript.js:153
contentscript.js:161:15

Works fine in current Fx stable release.

**Comment by tomayac** [comment]
As you write, this works fine in stable (70), but fails in 71. Since it's a [perfectly valid parameter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage#Parameters), I suggest you open a bug with Firefox. It was required for whatever reason when I developed this, but as it just sets the value to the default of `false`, this shouldn't fail. I'm closing here, please feel free to comment with the Firefox bug ID for people interested to follow this.

**Comment by tomayac** [comment]
FWIW, a work-in-progress fix addresses this with two ugly nested `try … catch` blocks (it's not been deployed to the add-on store yet, but works fine locally on both Firefox 70 and 71). 

https://github.com/google/service-worker-detector/blob/463d2b38ee024d591901775d73f90b54e63cb186/contentscript.js#L152-L163

**Comment by ghost** [comment]
This proxy API was removed: https://bugzilla.mozilla.org/show_bug.cgi?id=1443259

Why you are calling `sendMessage` with `null`?
