### ISSUE TITLE
Not working in latest FF

### ISSUE THREAD

**Issue by rawthriver** [google/service-worker-detector#16]
Firefox, console "Error: "Unexpected property toProxyScript"

**Comment by tomayac** [comment]
Sorry for the inconvenience, I've just submitted 2.3.17 to the Mozilla Add-on Store. It should be available and update automatically shortly.

https://addons.mozilla.org/en-US/firefox/addon/service-worker-detector/

Please comment on the issue should the problem still not be fixed in the new version.
